[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=10MB
loglevel=info

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.log

[program:keycloak]
command=/opt/start-keycloak.sh
autostart=true
autorestart=false
priority=20
stdout_logfile=/var/log/supervisor/keycloak.log
stderr_logfile=/var/log/supervisor/keycloak.log
startsecs=0

[program:springboot]
command=/opt/start-springboot.sh
autostart=true
autorestart=false
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=0
