ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS protein_g DECIMAL(8,2);
ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS carbs_g DECIMAL(8,2);
ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS fat_g DECIMAL(8,2);
ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS fiber_g DECIMAL(8,2);
ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS quantity VARCHAR(100);
ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS nutrition_details JSONB;
