ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS energy SMALLINT CHECK (energy BETWEEN 1 AND 5);
ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS wake_ups INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sleep_logs ADD COLUMN IF NOT EXISTS factors TEXT[];
