spring:
  flyway:
    validate-on-migrate: false

app:
  mail:
    security-alert-recipient: ilyassboulouiz@gmail.com

keycloak:
  admin:
    password: ${KC_BOOTSTRAP_ADMIN_PASSWORD:}

server:
  forward-headers-strategy: FRAMEWORK

logging:
  level:
    com.smartlife: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
