spring:
  flyway:
    validate-on-migrate: false
  data:
    redis:
      url: ${REDIS_URL:}

app:
  mail:
    security-alert-recipient: ilyassboulouiz@gmail.com

keycloak:
  admin:
    password: ${KC_BOOTSTRAP_ADMIN_PASSWORD:}

server:
  forward-headers-strategy: FRAMEWORK

logging:
  level:
    com.smartlife: INFO
    org.springframework.security: WARN
    org.springframework.security.oauth2.client: WARN
    io.opentelemetry: DEBUG
    io.micrometer.tracing: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/traces"
      headers:
        Authorization: "Basic ${OTLP_TOKEN:}"

sentry:
  dsn: ${SENTRY_DSN:}
  enabled: false
  traces-sample-rate: 0.1
  environment: production

